In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('data_students_performance.csv')

In [3]:
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [5]:
df.drop('gender',axis=1)

,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,group B,bachelor's degree,standard,none,72,72,74
1,group C,some college,standard,completed,69,90,88
2,group B,master's degree,standard,none,90,95,93
3,group A,associate's degree,free/reduced,none,47,57,44
4,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...
995,group E,master's degree,standard,completed,88,99,95
996,group C,high school,free/reduced,none,62,55,55
997,group C,high school,free/reduced,completed,59,71,65
998,group D,some college,standard,completed,68,78,77
999,group D,some college,free/reduced,none,77,86,86

In [8]:
df.groupby('race/ethnicity')['math score'].describe()

                count       mean        std   min    25%   50%   75%    max
race/ethnicity
group A          89.0  61.629213  14.523008  28.0  51.00  61.0  71.0  100.0
group B         190.0  63.452632  15.468191   8.0  54.00  63.0  74.0   97.0
group C         319.0  64.463950  14.852666   0.0  55.00  65.0  74.0   98.0
group D         262.0  67.362595  13.769386  26.0  59.00  69.0  77.0  100.0
group E         140.0  73.821429  15.534259  30.0  64.75  74.5  85.0  100.0

In [9]:
df.groupby('race/ethnicity')['reading score'].describe()

                count       mean        std   min    25%   50%    75%    max
race/ethnicity
group A          89.0  64.674157  15.543762  23.0  53.00  64.0  74.00  100.0
group B         190.0  67.352632  15.177499  24.0  56.00  67.0  79.75   97.0
group C         319.0  69.103448  13.997033  17.0  60.00  71.0  78.50  100.0
group D         262.0  70.030534  13.895306  31.0  60.25  71.0  79.00  100.0
group E         140.0  73.028571  14.874024  26.0  63.00  74.0  84.00  100.0

In [10]:
df.groupby('race/ethnicity')['reading score'].describe().transpose()

race/ethnicity     group A     group B     group C     group D     group E
count            89.000000  190.000000  319.000000  262.000000  140.000000
mean             64.674157   67.352632   69.103448   70.030534   73.028571
std              15.543762   15.177499   13.997033   13.895306   14.874024
min              23.000000   24.000000   17.000000   31.000000   26.000000
25%              53.000000   56.000000   60.000000   60.250000   63.000000
50%              64.000000   67.000000   71.000000   71.000000   74.000000
75%              74.000000   79.750000   78.500000   79.000000   84.000000
max             100.000000   97.000000  100.000000  100.000000  100.000000

In [20]:
df.groupby('race/ethnicity').describe()

               math score                                                 \
                    count       mean        std   min    25%   50%   75%
race/ethnicity
group A              89.0  61.629213  14.523008  28.0  51.00  61.0  71.0
group B             190.0  63.452632  15.468191   8.0  54.00  63.0  74.0
group C             319.0  64.463950  14.852666   0.0  55.00  65.0  74.0
group D             262.0  67.362595  13.769386  26.0  59.00  69.0  77.0
group E             140.0  73.821429  15.534259  30.0  64.75  74.5  85.0

                      reading score             ...                \
                  max         count       mean  ...    75%    max
race/ethnicity                                  ...
group A         100.0          89.0  64.674157  ...  74.00  100.0
group B          97.0         190.0  67.352632  ...  79.75   97.0
group C          98.0         319.0  69.103448  ...  78.50  100.0
group D         100.0         262.0  70.030534  ...  79.00  100.0
group E         100.0         140.0  73.028571  ...  84.00  100.0

               writing score                                                  \
                       count       mean        std   min    25%   50%    75%
race/ethnicity
group A                 89.0  62.674157  15.468278  19.0  51.00  62.0  73.00
group B                190.0  65.600000  15.625173  15.0  55.25  67.0  78.00
group C                319.0  67.827586  14.983378  10.0  57.00  68.0  79.00
group D                262.0  70.145038  14.367707  32.0  61.00  72.0  80.00
group E                140.0  71.407143  15.113906  22.0  62.00  72.0  80.25


                  max
race/ethnicity
group A          97.0
group B          96.0
group C         100.0
group D         100.0
group E         100.0

[5 rows x 24 columns]

In [16]:
df2 = pd.read_csv('data_iris.csv')
df2.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [17]:
df2.groupby('species')['sepal_length'].describe()

            count   mean       std  min    25%  50%  75%  max
species
setosa       50.0  5.006  0.352490  4.3  4.800  5.0  5.2  5.8
versicolor   50.0  5.936  0.516171  4.9  5.600  5.9  6.3  7.0
virginica    50.0  6.588  0.635880  4.9  6.225  6.5  6.9  7.9

In [19]:
df2.groupby('species').describe()

           sepal_length                                              \
                  count   mean       std  min    25%  50%  75%  max
species
setosa             50.0  5.006  0.352490  4.3  4.800  5.0  5.2  5.8
versicolor         50.0  5.936  0.516171  4.9  5.600  5.9  6.3  7.0
virginica          50.0  6.588  0.635880  4.9  6.225  6.5  6.9  7.9

           sepal_width         ... petal_length      petal_width         \
                 count   mean  ...          75%  max       count   mean
species                        ...
setosa            50.0  3.418  ...        1.575  1.9        50.0  0.244
versicolor        50.0  2.770  ...        4.600  5.1        50.0  1.326
virginica         50.0  2.974  ...        5.875  6.9        50.0  2.026


                 std  min  25%  50%  75%  max
species
setosa      0.107210  0.1  0.2  0.2  0.3  0.6
versicolor  0.197753  1.0  1.2  1.3  1.5  1.8
virginica   0.274650  1.4  1.8  2.0  2.3  2.5

[3 rows x 32 columns]